//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsosApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int Id { get; set; }
        public int ModemId { get; set; }
        public string Name { get; set; }
        public string SerialNo { get; set; }
        public int BrandId { get; set; }
        public string Model { get; set; }
        public bool IsProduction { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
    
        public virtual EnumDeviceBrand EnumDeviceBrand { get; set; }
        public virtual Modem Modem { get; set; }
    }
}
